Update notifications.json
RedisInsight/Notifications pull request #11
Opened 2022-08-31 15:30 UTC by ViktarStarastsenka

2022-08-31 16:25 UTC, K-Jo requested changes

2022-08-31 16:25 UTC, K-Jo commented on notifications.json
> +            "title": "Have an idea or a bug?",
feature not idea

2022-08-31 16:25 UTC, K-Jo commented on notifications.json
> +            "body": "Would you like to see specific features added or have a bug to report? <p> <a href="https://github.com/RedisInsight/RedisInsight">Share</a> it with us! <p> And star a repository
And star the repository if you like RedisInsight

2022-09-01 05:21 UTC, arthosofteq requested changes
I highly recommend to use editor that supports json or some online json validator like https://jsonlint.com/

2022-09-01 05:21 UTC, arthosofteq commented on notifications.json
> +            "body": "Would you like to see specific features added or have a bug to report? <p> <a href="https://github.com/RedisInsight/RedisInsight">Share</a> it with us! <p> And star the repositor
This is not a valid json. We have tests failed. Please escape `"` char with `\"` inside strings.
`"Would you like to see specific features added or have a bug to report? <p> <a href="https://github.com/RedisInsight/RedisInsight">Share</a> it with us! <p> And star the repository if you like RedisInsight!",`
should be 
`"Would you like to see specific features added or have a bug to report? <p> <a href=\"https://github.com/RedisInsight/RedisInsight">Share</a> it with us! <p> And star the repository if you like RedisInsight!\"",`

2022-09-01 06:54 UTC, arthosofteq commented on notifications.json
> +            "body": "Would you like to see specific features added or have a bug to report? <p> <a href="https://github.com/RedisInsight/RedisInsight">Share</a> it with us! <p> And star the repositor
UPD: Here is the correct json with `"` escaped
`"Would you like to see specific features added or have a bug to report? <p> <a href=\"https://github.com/RedisInsight/RedisInsight\">Share</a> it with us! <p> And star the repository if you like RedisInsight!"`

2022-09-01 09:40 UTC, arthosofteq approved these changes

2022-09-05 10:06 UTC, K-Jo approved these changes

2022-09-05 10:06 UTC, K-Jo commented on notifications.json
> +            "title": "Have a feature or a bug?",
Missing feature or found a bug?

2022-09-05 10:14 UTC, arthosofteq approved these changes

2022-09-05 11:20 UTC, arthosofteq approved these changes

2022-09-05 11:20 UTC, merged